<?php echo $this->docType('XHTML1_STRICT'); ?>
<html>
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
        
    </head>
    <body>
        <div id="container">
            <div id="header"><?=$this->action('login','index','sequrity')?></div>
            <div id="content">
                <?php echo $this->layout()->content ?>
            </div>
            <div id="footer"></div>
        </div>
    </body>
</html>
